spring.application.name=fresh-message
server.port=8085

spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.enabled=true

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6380
spring.data.redis.database=0

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/fresh_message?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis-plus.mapper-locations=classpath:mapper/**/*.xml
mybatis-plus.type-aliases-package=com.fresh.message.entity

spring.cloud.openfeign.client.config.fresh-user.url=http://127.0.0.1:8081
spring.cloud.openfeign.client.config.fresh-order.url=http://127.0.0.1:8083

spring.cloud.stream.function.definition=orderCreateConsumer;orderSuccessConsumer;orderUnpaidConsumer;integralChangeConsumer;couponReceiveConsumer;commentAddConsumer;aiRecognizeFinishConsumer
spring.cloud.stream.rocketmq.binder.name-server=127.0.0.1:9876
spring.cloud.stream.bindings.orderCreateConsumer-in-0.destination=ORDER_CREATE_TOPIC
spring.cloud.stream.bindings.orderCreateConsumer-in-0.group=fresh-message-order-create-group
spring.cloud.stream.bindings.orderSuccessConsumer-in-0.destination=ORDER_SUCCESS_TOPIC
spring.cloud.stream.bindings.orderSuccessConsumer-in-0.group=fresh-message-order-success-group
spring.cloud.stream.bindings.orderUnpaidConsumer-in-0.destination=ORDER_UNPAID_TOPIC
spring.cloud.stream.bindings.orderUnpaidConsumer-in-0.group=fresh-message-order-unpaid-group
spring.cloud.stream.bindings.integralChangeConsumer-in-0.destination=INTEGRAL_CHANGE_TOPIC
spring.cloud.stream.bindings.integralChangeConsumer-in-0.group=fresh-message-integral-group
spring.cloud.stream.bindings.couponReceiveConsumer-in-0.destination=COUPON_RECEIVE_TOPIC
spring.cloud.stream.bindings.couponReceiveConsumer-in-0.group=fresh-message-coupon-group
spring.cloud.stream.bindings.commentAddConsumer-in-0.destination=COMMENT_ADD_TOPIC
spring.cloud.stream.bindings.commentAddConsumer-in-0.group=fresh-message-comment-group
spring.cloud.stream.bindings.aiRecognizeFinishConsumer-in-0.destination=AI_RECOGNIZE_FINISH_TOPIC
spring.cloud.stream.bindings.aiRecognizeFinishConsumer-in-0.group=fresh-message-ai-group

logging.level.com.fresh.message=DEBUG
